<a href="https://colab.research.google.com/github/rosiecao/Team_Final_Project/blob/main/GWU_Data_Analytics_Final_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Final Project 

## Purpose of this final project

* Purpose of this final project is to apply foundational skills learned during this certificate program.

## About the Team

The team is composed of three students that are a part of the July 2021 - Febraury 2022 GWU Data Analytics Professional Certificate cohort. These students include:

1. Shamir Parham
> To access Shamir's GitHub account, to see all his program- or work-related projects, you can go [here](https://github.com/Shamirp).

2. Bailey Adkins
> To access Bailey's GitHub account, to see all his program- or work-related projects, you can go [here](https://github.com/badkins2908).

## Role Assignments

Square: Rosie

*The team member in the square role will be responsible for the repository. As well as for the visualization of the data.*

Triangle: Shamir

*The member in the triangle role will create a mockup of a machine learning model. This can even be a diagram that explains how it will work concurrently with the rest of the project steps.*

Circle: Bailey

*The member in the circle role will create a mockup of a database with a set of sample data, or even fabricated data. This will ensure the database will work seamlessly with the rest of the project.*

X: Whole Team

*The whole team will decide on best technologies to use for each stage of the project.*

## GitHub Repository

The following GitHub Respositories for Final Project:

Main Repository: https://github.com/rosiecao/Team_Final_Project

Shamir's Branch: https://github.com/rosiecao/Team_Final_Project/tree/Shamir

Bailey's Branch: https://github.com/rosiecao/Team_Final_Project/tree/Bailey

## Topic, Data Sources, and Technologies

1. Selected topic and reason for topic selected
> We chose for our final project to clean and combine county property value assessment data, crime data, and community resiliency indicator data for San Francisco. This data will then be visualized in Tableau, such that when looking at the best areas to potentially move to or live in, property values, crime data for the area and environmental health of that neighborhood can all be taken into account to make the best decision on where to live. This topic was chosen due to the readily available data, as well as an interest in seeing if this information will come together in a truly useful way.


> > > Previous work in this space: There has been a degree of previous work in the space. [Realtor.com](https://www.npr.org/2020/08/26/905551631/major-real-estate-website-now-shows-flood-risk-should-they-all) does have an incorporated feature that tells the risk of a property to flood. In addition, [HouseCanary](https://www.housecanary.com/products/data-points/) does have the data points our project is looking to present, but you need to pay access to their database and the data is presented per house and not as map layers. 


2. Sources of data

> * Property Value data: https://data.sfgov.org/Housing-and-Buildings/Assessor-Historical-Secured-Property-Tax-Rolls/wv5m-vpq2/data

> * San Francisco crime data: https://data.sfgov.org/Public-Safety/Map-of-Police-Department-Incident-Reports-2018-to-/jq29-s5wp

> * Community Resiliency: https://data.sfgov.org/Health-and-Social-Services/Community-Resiliency-Indicator-System/banc-xdvr/data 

> * San Francisco neighborhood geo data: https://data.sfgov.org/Geographic-Locations-and-Boundaries/Analysis-Neighborhoods-2010-census-tracts-assigned/bwbp-wk3r

3. Questions we hope to answer with the data
> We are hoping this project will allow individuals interested in real estate in San Fransico to also take into account crime data for the area, property values of the area, as well as potential for environmental health factors of the area, to aid in their purchasing or rental decision making process.

4. Technologies for each stage

> * Evaluating the datasets, Data Cleaning and Exploratory Analysis: 
Python will be used to import csv files to dataframes, to explore and clean data in order to establish a good dataset to import into database tables.

> * Database Storage: The data will be stores in sqLite database.

> * Machine Learning
SciKitLearn is the ML library we'll be using to create a classifier. Our training and testing setup is ___. Extra ML verbiage here.

> * Dashboard: 
GeoJSON will be used with HTML and CSS to present overlapping layers on a interactive map. (or Tableau will be used to visualize the different layers on an interactive map of San Francisco)

## Database Model + Data Dictionary

To see the visual schema of the sqLite database, as well the data dictionary for each dataset (table): [DB Schema](https://drive.google.com/file/d/1zMCzaFGsRjlVzsnGYrUh8-SjzrpvTqhi/view?usp=sharing)

Further data descriptions for Resiliency, can be found [here](https://data.sfgov.org/api/views/banc-xdvr/files/JThIwZSDAm5AAw087Uwi2lZDUevVQqy1br38NZtJOqs?download=true&filename=SFDPH_CommunityResiliencyIndicatorMethods.pdf).

Any additional information on datasets, including assessing the raw datasets can be found by following the links in the previous section under "Topic, Data Sources, and Technologies".

## Machine Learning Model

*Maybe we can look at doing a model that predicts the best houses to buy, based on cost, size, low crime, and low flooding risk? Or something along those lines?

* Can complete this by training multiple unsupervised machine learning models (Shamir POA)

# Data Exploration and Cleaning

### This will include importing the data in order to best understand how to load it into database tables, clean the data and then import into tables within sqLite database, then carry out any further exploratory analysis.

## Importing Data

In [150]:
# install condacolab
!pip install -q condacolab
import condacolab
condacolab.install()

‚ú®üç∞‚ú® Everything looks OK!

In [151]:
import pandas as pd
import json
import numpy as np

In [152]:
# First: Read in all csv data into dataframes in order to evaluate and clean
# CSV files are all within Google Drive this project is working out of, here: https://drive.google.com/drive/folders/1fNxRx1LUCMFouu3zLvGrsuTQgdpVJGX8

# May need to install PyDrive
#!pip install -U -q PyDrive

# Allow access to Google Drive to access csv files for project
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from google.colab import drive
from oauth2client.client import GoogleCredentials
  
  
# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [5]:
#from google.colab import drive
#drive.mount('/content/drive')

In [235]:
!conda install geopandas
import geopandas as gpd

Collecting package metadata (current_repodata.json): - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / done
Solving environment: \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ done
Solving environment: / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ done

## Package Plan ##

  environment location: /usr/local

  added / updated specs:
    - geopandas


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    attrs-21.4.0               |     pyhd8ed1ab_0          49 KB  conda-forge
    boost-cpp-1.74.0           |       hc6e9bd1_3        16.3 MB  conda-forge
    branca-0.4.2               |     pyhd8ed1ab_0          26 KB  conda-forge
    ca-certificates-2021.10.8  |       ha878542_0         139 KB  conda-forge
    cairo-1.16.0               |    h6cf1ce9_1008         1.5 MB  conda-forge
    certifi-2021.10.8          |   py37h89c1867_1         145 KB  conda-forge
    cfitsio-3.470              |       hb418390_7         1.3 MB  conda-forge
    click-7.1.2                |     pyh9f0ad1d_0          64 KB  conda-forge
    click-plugins-1.1.1        |             py_0           9 KB  conda-forge
    cligj-0.7.2                |     pyhd8ed1ab_1          10 KB  conda-forge
    conda-4.11.0               |   py37h89c1867_0        16.9 MB  conda-forge
    cudatoolkit-11.1.1         |       h6406543_8        1.20 GB  conda-forge
    curl-7.75.0                |       h979ede3_0         147 KB  conda-forge
    cycler-0.11.0              |     pyhd8ed1ab_0          10 KB  conda-forge
    expat-2.4.1                |       h9c3ff4c_0         182 KB  conda-forge
    fiona-1.8.20               |   py37ha0cc35a_0         1.1 MB  conda-forge

In [153]:
# Read in Tax Value Assessment data from Google Drive

link = 'https://drive.google.com/file/d/17inJxIv-Yogdc4yYhaPdqiAs4mQvolhw/view'
  
# to get the id part of the file
id = link.split("/")[-2]
  
downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('Assessor_Historical_Secured_Property_Tax_Rolls.csv')  
  
property_df = pd.read_csv('Assessor_Historical_Secured_Property_Tax_Rolls.csv')
print(property_df)

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (26) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

         Closed Roll Year  ... Neighborhoods
0                    2012  ...           NaN
1                    2013  ...           NaN
2                    2007  ...           NaN
3                    2014  ...           NaN
4                    2008  ...           NaN
...                   ...  ...           ...
2666112              2019  ...          64.0
2666113              2019  ...          65.0
2666114              2019  ...          43.0
2666115              2019  ...          62.0
2666116              2019  ...          65.0

[2666117 rows x 54 columns]

In [154]:
# Read in Crime data from Google Drive

link = 'https://drive.google.com/file/d/16DErDyTtvijVLeERbwbCJnW3SvhqE9a1/view'
  
# to get the id part of the file
id = link.split("/")[-2]
  
downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('Police_Department_Incident_Reports__2018_to_Present.csv')  
  
crime_df = pd.read_csv('Police_Department_Incident_Reports__2018_to_Present.csv')
print(crime_df)

             Incident Datetime  ... Current Police Districts
0       2019/03/05 09:00:00 PM  ...                      5.0
1       2018/12/22 12:00:00 PM  ...                      4.0
2       2018/08/24 05:30:00 PM  ...                      9.0
3       2018/10/20 03:10:00 PM  ...                      1.0
4       2019/06/05 12:36:00 AM  ...                      6.0
...                        ...  ...                      ...
547792  2021/01/15 08:00:00 PM  ...                      5.0
547793  2020/08/01 05:34:00 PM  ...                      8.0
547794  2020/06/01 01:55:00 AM  ...                      2.0
547795  2020/10/24 05:00:00 PM  ...                      4.0
547796  2020/11/19 08:30:00 AM  ...                      9.0

[547797 rows x 34 columns]

In [155]:
# Read in Community Resiliency data from Google Drive

link = 'https://drive.google.com/file/d/1igl3G39PQ7M26KIpsn5IpWeLOnZiU9rO/view?usp=sharing'
  
# to get the id part of the file
id = link.split("/")[-2]
  
downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('Community_Resiliency_Indicator_System.csv')  
  
community_df = pd.read_csv('Community_Resiliency_Indicator_System.csv')
print(community_df)

                 Neighborhood  Flood_Per  ...  Res_Score  Res_Rank
0                     Bayview   0.068369  ...        1.0      35.0
1              Bernal Heights   0.000000  ...        3.0      16.0
2         Castro/Upper Market   0.000000  ...        5.0       2.0
3                   Chinatown   0.000000  ...        1.0      36.0
4              Crocker Amazon   0.000000  ...        1.0      30.0
5   Diamond Heights/Glen Park   0.000000  ...        5.0       5.0
6       Downtown/Civic Center   0.000000  ...        1.0      34.0
7                   Excelsior   0.000000  ...        2.0      29.0
8          Financial District   0.026447  ...        1.0      31.0
9            Golden Gate Park   0.022587  ...        NaN       NaN
10             Haight Ashbury   0.000000  ...        5.0       4.0
11             Inner Richmond   0.000000  ...        4.0      15.0
12               Inner Sunset   0.000000  ...        4.0      10.0
13                  Lakeshore   0.008689  ...        2.0      23.0
14                     Marina   0.007152  ...        4.0       9.0
15                    Mission   0.000000  ...        2.0      25.0
16                Mission Bay   0.132514  ...        3.0      17.0
17                   Nob Hill   0.000000  ...        3.0      19.0
18                 Noe Valley   0.000000  ...        5.0       3.0
19                North Beach   0.011395  ...        2.0      24.0
20                 Ocean View   0.000000  ...        2.0      27.0
21              Outer Mission   0.000000  ...        2.0      26.0
22             Outer Richmond   0.015642  ...        3.0      18.0
23               Outer Sunset   0.017670  ...        3.0      20.0
24            Pacific Heights   0.000000  ...        5.0       7.0
25                   Parkside   0.009789  ...        3.0      22.0
26               Potrero Hill   0.010071  ...        4.0      13.0
27                   Presidio   0.029715  ...        5.0       1.0
28           Presidio Heights   0.000000  ...        4.0      11.0
29               Russian Hill   0.002798  ...        4.0      14.0
30                   Seacliff   0.037849  ...        5.0       6.0
31            South of Market   0.002380  ...        2.0      28.0
32        Treasure Island YBI   0.262905  ...        1.0      32.0
33                 Twin Peaks   0.000000  ...        4.0      12.0
34          Visitacion Valley   0.000000  ...        1.0      33.0
35         West of Twin Peaks   0.000000  ...        5.0       8.0
36           Western Addition   0.000000  ...        3.0      21.0

[37 rows x 51 columns]

In [156]:
# Read in Neighboor data from Google Drive

link = 'https://drive.google.com/file/d/1GFoP_cdmebMH2fFb7LjQeFtbgfQR4qQ_/view'
  
# to get the id part of the file
id = link.split("/")[-2]
  
downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('Analysis_Neighborhoods.csv')  
  
neighborhood_df = pd.read_csv('Analysis_Neighborhoods.csv')

neighborhood_df.head()

                                            the_geom  ...     SHAPE_LEN
0  MULTIPOLYGON (((-122.43246699970955 37.7737570...  ...   7589.679396
1  MULTIPOLYGON (((-122.4235409996432 37.77967400...  ...   8525.808755
2  MULTIPOLYGON (((-122.42468700019211 37.7853350...  ...   8000.966619
3  MULTIPOLYGON (((-122.42468700019211 37.7853350...  ...  12144.016761
4  MULTIPOLYGON (((-122.43491799981281 37.7858759...  ...   6918.268026

[5 rows x 6 columns]

## Prepping Tax Property Value Dataset

In [157]:
property_df.head(5)

   Closed Roll Year  ... Neighborhoods
0              2012  ...           NaN
1              2013  ...           NaN
2              2007  ...           NaN
3              2014  ...           NaN
4              2008  ...           NaN

[5 rows x 54 columns]

In [158]:
# seeing what values are in each main column

print("Use definition: ", property_df['Use Definition'].unique())
print("Years of assessment: ", property_df['Closed Roll Year'].unique())

Use definition:  [nan 'Commercial Misc' 'Single Family Residential' 'Government'
 'Miscellaneous/Mixed-Use' 'Multi-Family Residential' 'Commercial Office'
 'Commercial Retail' 'Commercial Hotel' 'Industrial']
Years of assessment:  [2012 2013 2007 2014 2008 2010 2009 2017 2019 2015 2018 2016 2011]

In [159]:
# creating dataframe only for single family residential & multi-family residential
famprop_df = property_df[(property_df['Use Definition'] == "Multi-Family Residential") | (property_df['Use Definition'] == 'Single Family Residential')]

famprop_df.head()

    Closed Roll Year  ... Neighborhoods
14              2019  ...           NaN
38              2019  ...           NaN
53              2007  ...           NaN
64              2008  ...           NaN
79              2007  ...           NaN

[5 rows x 54 columns]

In [160]:
# counting unique values in the_geom
n = len(pd.unique(famprop_df['the_geom']))
total_rows = len(famprop_df)
  
print("No.of.unique values for geo location :", 
      n, "out of ", total_rows)


# get the number fo NaN values in main columns
na_rows = famprop_df['the_geom'].isna().sum()
print("No.of.null values for geo location :", 
      na_rows, "out of ", total_rows)

No.of.unique values for geo location : 139555 out of  2343825
No.of.null values for geo location : 330 out of  2343825

In [161]:
# filter out geo locations that are null
famprop_df = famprop_df[famprop_df.the_geom.notnull()]

In [162]:
# after dropping nulls, get the number fo NaN values in main columns
na_rows = famprop_df['the_geom'].isna().sum()
print("No.of.null values for geo location :", 
      na_rows, "out of ", total_rows)

No.of.null values for geo location : 0 out of  2343825

In [163]:
# Counting unique values in Neighborhood
n = len(pd.unique(famprop_df['Analysis Neighborhood']))
total_rows = len(famprop_df)
  
print("No.of.unique values for neighborhoods:", 
      n, "out of ", total_rows)


# Get the number fo NaN values in main columns
na_rows = famprop_df['Analysis Neighborhood'].isna().sum()
print("No.of.null values for neighborhoods :", 
      na_rows, "out of ", total_rows)

No.of.unique values for neighborhoods: 40 out of  2343495
No.of.null values for neighborhoods : 0 out of  2343495

In [164]:
famprop_df.head()

     Closed Roll Year  ... Neighborhoods
180              2011  ...         107.0
183              2011  ...          18.0
184              2011  ...         106.0
185              2011  ...         106.0
186              2011  ...         107.0

[5 rows x 54 columns]

In [165]:
famprop_df = famprop_df.sort_values('Analysis Neighborhood')

In [166]:
famprop_df['Analysis Neighborhood'].unique()

array(['Bayview Hunters Point', 'Bernal Heights', 'Castro/Upper Market',
       'Chinatown', 'Excelsior', 'Financial District/South Beach',
       'Glen Park', 'Golden Gate Park', 'Haight Ashbury', 'Hayes Valley',
       'Inner Richmond', 'Inner Sunset', 'Japantown', 'Lakeshore',
       'Lincoln Park', 'Lone Mountain/USF', 'Marina', 'McLaren Park',
       'Mission', 'Mission Bay', 'Nob Hill', 'Noe Valley', 'North Beach',
       'Oceanview/Merced/Ingleside', 'Outer Mission', 'Outer Richmond',
       'Pacific Heights', 'Portola', 'Potrero Hill', 'Presidio',
       'Presidio Heights', 'Russian Hill', 'Seacliff', 'South of Market',
       'Sunset/Parkside', 'Tenderloin', 'Twin Peaks', 'Visitacion Valley',
       'West of Twin Peaks', 'Western Addition'], dtype=object)

In [167]:
# drop unneccessary columns

famprop_df.drop('DELETE - Supervisor Districts 2', axis=1, inplace=True)
famprop_df.drop('DELETE - Fire Prevention Districts 2', axis=1, inplace=True)
famprop_df.drop('DELETE - Current Police Districts 2', axis=1, inplace=True)
famprop_df.drop('DELETE - Zip Codes 2', axis=1, inplace=True)
famprop_df.drop('DELETE - Neighborhoods 2', axis=1, inplace=True)
famprop_df.drop('DELETE - Police Districts 2', axis=1, inplace=True)
famprop_df.drop('Row ID', axis=1, inplace=True)
famprop_df.drop('SF Find Neighborhoods 2', axis=1, inplace=True)
famprop_df.drop('Current Police Districts 2', axis=1, inplace=True)
famprop_df.drop('Current Supervisor Districts 2', axis=1, inplace=True)
famprop_df.drop('Analysis Neighborhoods 2', axis=1, inplace=True)
famprop_df.drop('Neighborhoods', axis=1, inplace=True)

In [168]:
famprop_df.head()

         Closed Roll Year  ...                                       the_geom
949125               2008  ...      POINT (-122.393061863214 37.732406652893)
1574636              2012  ...      POINT (-122.372272513207 37.726990601916)
1962114              2014  ...    POINT (-122.39196042114202 37.732201467133)
1146727              2009  ...  POINT (-122.39583604533802 37.73555591788201)
1962113              2014  ...       POINT (-122.39881567547 37.738769700915)

[5 rows x 42 columns]

In [169]:
famprop_df.dtypes

Closed Roll Year                      int64
Property Location                    object
Parcel Number                        object
Block                                object
Lot                                  object
Volume Number                         int64
Use Code                             object
Use Definition                       object
Property Class Code                  object
Property Class Code Definition       object
Year Property Built                 float64
Number of Bathrooms                 float64
Number of Bedrooms                    int64
Number of Rooms                     float64
Number of Stories                   float64
Number of Units                       int64
Zoning Code                          object
Construction Type                    object
Lot Depth                           float64
Lot Frontage                        float64
Property Area                         int64
Basement Area                       float64
Lot Area                            float64
Lot Code                             object
Tax Rate Area Code                  float64
Percent of Ownership                float64
Exemption Code                       object
Exemption Code Definition            object
Status Code                          object
Misc Exemption Value                  int64
Homeowner Exemption Value           float64
Current Sales Date                   object
Assessed Fixtures Value               int64
Assessed Improvement Value            int64
Assessed Land Value                   int64
Assessed Personal Property Value      int64
Assessor Neighborhood District      float64
Assessor Neighborhood Code           object
Assessor Neighborhood                object
Supervisor District                 float64
Analysis Neighborhood                object
the_geom                             object
dtype: object

In [170]:
#convert POINT data to string in order to break out into lat long
famprop_df['the_geom'].astype(str)

949125         POINT (-122.393061863214 37.732406652893)
1574636        POINT (-122.372272513207 37.726990601916)
1962114      POINT (-122.39196042114202 37.732201467133)
1146727    POINT (-122.39583604533802 37.73555591788201)
1962113         POINT (-122.39881567547 37.738769700915)
                               ...
1242238        POINT (-122.430145213421 37.784091979856)
1242242        POINT (-122.431977000417 37.781951305255)
462183          POINT (-122.43811123286 37.782096009826)
2487273         POINT (-122.421406325843 37.78138577763)
234020         POINT (-122.424224918217 37.786755277916)
Name: the_geom, Length: 2343495, dtype: object

In [171]:
# Split out POINT data into lat long coordinates or regular expression

famprop_df[['Point', 'Full LatLong']] = famprop_df['the_geom'].str.split('(', expand=True)

famprop_df[['Longitude', 'LatitudeFull']] = famprop_df['Full LatLong'].str.split(' ', expand=True)

famprop_df['Latitude']= famprop_df['LatitudeFull'].str.rstrip(')')

In [172]:
famprop_df

         Closed Roll Year  ...           Latitude
949125               2008  ...    37.732406652893
1574636              2012  ...    37.726990601916
1962114              2014  ...    37.732201467133
1146727              2009  ...  37.73555591788201
1962113              2014  ...    37.738769700915
...                   ...  ...                ...
1242238              2010  ...    37.784091979856
1242242              2010  ...    37.781951305255
462183               2017  ...    37.782096009826
2487273              2019  ...     37.78138577763
234020               2016  ...    37.786755277916

[2343495 rows x 47 columns]

In [173]:
# Convert Lat Long back to numberic (float)
famprop_df['Longitude'] = pd.to_numeric(famprop_df['Longitude'])
famprop_df['Latitude'] = pd.to_numeric(famprop_df['Latitude'])

In [174]:
famprop_df.dtypes

Closed Roll Year                      int64
Property Location                    object
Parcel Number                        object
Block                                object
Lot                                  object
Volume Number                         int64
Use Code                             object
Use Definition                       object
Property Class Code                  object
Property Class Code Definition       object
Year Property Built                 float64
Number of Bathrooms                 float64
Number of Bedrooms                    int64
Number of Rooms                     float64
Number of Stories                   float64
Number of Units                       int64
Zoning Code                          object
Construction Type                    object
Lot Depth                           float64
Lot Frontage                        float64
Property Area                         int64
Basement Area                       float64
Lot Area                            float64
Lot Code                             object
Tax Rate Area Code                  float64
Percent of Ownership                float64
Exemption Code                       object
Exemption Code Definition            object
Status Code                          object
Misc Exemption Value                  int64
Homeowner Exemption Value           float64
Current Sales Date                   object
Assessed Fixtures Value               int64
Assessed Improvement Value            int64
Assessed Land Value                   int64
Assessed Personal Property Value      int64
Assessor Neighborhood District      float64
Assessor Neighborhood Code           object
Assessor Neighborhood                object
Supervisor District                 float64
Analysis Neighborhood                object
the_geom                             object
Point                                object
Full LatLong                         object
Longitude                           float64
LatitudeFull                         object
Latitude                            float64
dtype: object

In [175]:
# Drop extra columns made from creating lat long
famprop_df.drop('Point', axis=1, inplace=True)
famprop_df.drop('Full LatLong', axis=1, inplace=True)
famprop_df.drop('LatitudeFull', axis=1, inplace=True)

famprop_df

         Closed Roll Year  ...   Latitude
949125               2008  ...  37.732407
1574636              2012  ...  37.726991
1962114              2014  ...  37.732201
1146727              2009  ...  37.735556
1962113              2014  ...  37.738770
...                   ...  ...        ...
1242238              2010  ...  37.784092
1242242              2010  ...  37.781951
462183               2017  ...  37.782096
2487273              2019  ...  37.781386
234020               2016  ...  37.786755

[2343495 rows x 44 columns]

In [176]:
# add average assessment across all san fran
famprop_df['TotalAssessedValue'] = famprop_df['Assessed Improvement Value'] + famprop_df['Assessed Land Value']

# add average assessment across all san fran
famprop_df['Total Avg Assessed'] = famprop_df['TotalAssessedValue'].mean(axis=0)

# Average assessment across all san fran neighborhoods
famprop_df['Avg Home Cost'] = famprop_df.groupby(['Analysis Neighborhood']).TotalAssessedValue.transform('mean')
#print(famprop_df['Avg Home Cost'])

In [177]:
famprop_df.head()

         Closed Roll Year  ... Avg Home Cost
949125               2008  ...  349602.14105
1574636              2012  ...  349602.14105
1962114              2014  ...  349602.14105
1146727              2009  ...  349602.14105
1962113              2014  ...  349602.14105

[5 rows x 47 columns]

In [178]:
famprop_df = famprop_df.rename(columns = {'Analysis Neighborhood' : 'AnalysisNeighborhood'})

In [179]:
famprop_df.columns

Index(['Closed Roll Year', 'Property Location', 'Parcel Number', 'Block',
       'Lot', 'Volume Number', 'Use Code', 'Use Definition',
       'Property Class Code', 'Property Class Code Definition',
       'Year Property Built', 'Number of Bathrooms', 'Number of Bedrooms',
       'Number of Rooms', 'Number of Stories', 'Number of Units',
       'Zoning Code', 'Construction Type', 'Lot Depth', 'Lot Frontage',
       'Property Area', 'Basement Area', 'Lot Area', 'Lot Code',
       'Tax Rate Area Code', 'Percent of Ownership', 'Exemption Code',
       'Exemption Code Definition', 'Status Code', 'Misc Exemption Value',
       'Homeowner Exemption Value', 'Current Sales Date',
       'Assessed Fixtures Value', 'Assessed Improvement Value',
       'Assessed Land Value', 'Assessed Personal Property Value',
       'Assessor Neighborhood District', 'Assessor Neighborhood Code',
       'Assessor Neighborhood', 'Supervisor District', 'AnalysisNeighborhood',
       'the_geom', 'Longitude', 'Latitude', 'TotalAssessedValue',
       'Total Avg Assessed', 'Avg Home Cost'],
      dtype='object')

In [180]:
# export to csv and download
from google.colab import files
famprop_df.to_csv('Property Assessment Final.csv') 
files.download('Property Assessment Final.csv')

In [181]:
#Dropping columns to create dataframe for machine learning model
cleanprop_df = famprop_df.drop(columns = ['Closed Roll Year', 'Property Location', 'Parcel Number', 'Block',
       'Lot', 'Volume Number', 'Use Code', 'Use Definition',
       'Property Class Code', 'Property Class Code Definition',
       'Year Property Built', 'Number of Bathrooms', 'Number of Bedrooms',
       'Number of Rooms', 'Number of Stories', 'Number of Units',
       'Zoning Code', 'Construction Type', 'Lot Depth', 'Lot Frontage',
       'Property Area', 'Basement Area', 'Lot Area', 'Lot Code',
       'Tax Rate Area Code', 'Percent of Ownership', 'Exemption Code',
       'Exemption Code Definition', 'Status Code', 'Misc Exemption Value',
       'Homeowner Exemption Value', 'Current Sales Date',
       'Assessed Fixtures Value', 'Assessed Improvement Value',
       'Assessed Land Value', 'Assessed Personal Property Value',
       'Assessor Neighborhood District', 'Assessor Neighborhood Code',
       'Assessor Neighborhood', 'Supervisor District',
       'the_geom', 'Latitude', 'Longitude','TotalAssessedValue', 'Total Avg Assessed',
       'TotalAssessedValue'])

In [182]:
cleanprop_df.head()

          AnalysisNeighborhood  Avg Home Cost
949125   Bayview Hunters Point   349602.14105
1574636  Bayview Hunters Point   349602.14105
1962114  Bayview Hunters Point   349602.14105
1146727  Bayview Hunters Point   349602.14105
1962113  Bayview Hunters Point   349602.14105

In [183]:
cleanprop_df['AnalysisNeighborhood'].unique()

array(['Bayview Hunters Point', 'Bernal Heights', 'Castro/Upper Market',
       'Chinatown', 'Excelsior', 'Financial District/South Beach',
       'Glen Park', 'Golden Gate Park', 'Haight Ashbury', 'Hayes Valley',
       'Inner Richmond', 'Inner Sunset', 'Japantown', 'Lakeshore',
       'Lincoln Park', 'Lone Mountain/USF', 'Marina', 'McLaren Park',
       'Mission', 'Mission Bay', 'Nob Hill', 'Noe Valley', 'North Beach',
       'Oceanview/Merced/Ingleside', 'Outer Mission', 'Outer Richmond',
       'Pacific Heights', 'Portola', 'Potrero Hill', 'Presidio',
       'Presidio Heights', 'Russian Hill', 'Seacliff', 'South of Market',
       'Sunset/Parkside', 'Tenderloin', 'Twin Peaks', 'Visitacion Valley',
       'West of Twin Peaks', 'Western Addition'], dtype=object)

In [184]:
mlprop_df = (cleanprop_df.rename(columns = {'Analysis Neighborhood' : 'AnalysisNeighborhood', 'Avg Home Cost' : 'AvgHomeCost'}))
mlprop_df.head()

          AnalysisNeighborhood   AvgHomeCost
949125   Bayview Hunters Point  349602.14105
1574636  Bayview Hunters Point  349602.14105
1962114  Bayview Hunters Point  349602.14105
1146727  Bayview Hunters Point  349602.14105
1962113  Bayview Hunters Point  349602.14105

In [185]:
mlprop_df.dtypes

AnalysisNeighborhood     object
AvgHomeCost             float64
dtype: object

In [186]:
mlprop_df = mlprop_df.drop_duplicates(subset=['AnalysisNeighborhood'])

In [187]:
mlprop_df

                   AnalysisNeighborhood   AvgHomeCost
949125            Bayview Hunters Point  3.496021e+05
1173084                  Bernal Heights  4.817842e+05
2149865             Castro/Upper Market  8.034330e+05
1011669                       Chinatown  9.457721e+05
986331                        Excelsior  3.444720e+05
198580   Financial District/South Beach  1.121083e+06
994773                        Glen Park  5.779448e+05
2303088                Golden Gate Park  4.224318e+06
2275690                  Haight Ashbury  8.288059e+05
1459292                    Hayes Valley  8.016554e+05
1685177                  Inner Richmond  6.943029e+05
1269346                    Inner Sunset  6.031309e+05
845761                        Japantown  5.065034e+05
1619852                       Lakeshore  2.803594e+06
2298675                    Lincoln Park  8.715481e+05
1057489               Lone Mountain/USF  6.551503e+05
2472815                          Marina  1.167930e+06
1599574                    McLaren Park  3.311654e+05
1941022                         Mission  6.340985e+05
547697                      Mission Bay  1.019381e+06
2048763                        Nob Hill  1.067856e+06
365723                       Noe Valley  7.476375e+05
408699                      North Beach  8.342235e+05
2656349      Oceanview/Merced/Ingleside  3.457159e+05
2452557                   Outer Mission  3.666917e+05
250986                   Outer Richmond  5.516745e+05
674988                  Pacific Heights  1.467162e+06
1579729                         Portola  3.583265e+05
1969252                    Potrero Hill  6.390039e+05
671626                         Presidio  3.636486e+06
1065161                Presidio Heights  1.458371e+06
2261076                    Russian Hill  1.013545e+06
1491141                        Seacliff  1.558257e+06
937016                  South of Market  8.435418e+05
484588                  Sunset/Parkside  4.284264e+05
2251737                      Tenderloin  1.505361e+06
96134                        Twin Peaks  6.522030e+05
2619186               Visitacion Valley  3.125011e+05
1511041              West of Twin Peaks  5.782016e+05
435613                 Western Addition  6.644454e+05

## Prepping Crime Dataset

In [188]:
crime_df.head()

        Incident Datetime  ... Current Police Districts
0  2019/03/05 09:00:00 PM  ...                      5.0
1  2018/12/22 12:00:00 PM  ...                      4.0
2  2018/08/24 05:30:00 PM  ...                      9.0
3  2018/10/20 03:10:00 PM  ...                      1.0
4  2019/06/05 12:36:00 AM  ...                      6.0

[5 rows x 34 columns]

In [189]:
crime_df = crime_df.sort_values('Analysis Neighborhood')

In [190]:
crime_df['Analysis Neighborhood'].unique()

array(['Bayview Hunters Point', 'Bernal Heights', 'Castro/Upper Market',
       'Chinatown', 'Excelsior', 'Financial District/South Beach',
       'Glen Park', 'Golden Gate Park', 'Haight Ashbury', 'Hayes Valley',
       'Inner Richmond', 'Inner Sunset', 'Japantown', 'Lakeshore',
       'Lincoln Park', 'Lone Mountain/USF', 'Marina', 'McLaren Park',
       'Mission', 'Mission Bay', 'Nob Hill', 'Noe Valley', 'North Beach',
       'Oceanview/Merced/Ingleside', 'Outer Mission', 'Outer Richmond',
       'Pacific Heights', 'Portola', 'Potrero Hill', 'Presidio',
       'Presidio Heights', 'Russian Hill', 'Seacliff', 'South of Market',
       'Sunset/Parkside', 'Tenderloin', 'Treasure Island', 'Twin Peaks',
       'Visitacion Valley', 'West of Twin Peaks', 'Western Addition', nan],
      dtype=object)

In [191]:
crime_df = crime_df.rename(columns = {'Analysis Neighborhood' : 'AnalysisNeighborhood'})

In [192]:
# filter out geo locations that are null
crime_df = crime_df[crime_df.AnalysisNeighborhood.notnull()]

In [193]:
# after dropping nulls, get the number fo NaN values in neighborhoods
na_rows = crime_df['AnalysisNeighborhood'].isna().sum()
print("No.of.null values for neighborhoods:", 
      na_rows)

No.of.null values for neighborhoods: 0

In [194]:
# New column for Incident Category Score

crime = { "violent": 
     ["Arson", "Assault", "Warrant", "Burglary", "Homicide", "Human Trafficking (A)", "Human Trafficking (B)", "Human Trafficking", "Missing Persons", "Motor Vehicle Theft", "Motor Vehicle Theft?", "Offenses Against The Family And Children", "Rape", "Weapons Offense"], 
  "disturbing-the-peace": 
     ["Drug Offense", "Disorderly Conduct", "Drug Violation", "Liquor Laws", "Malicious Mischief", "Sex Offense", "Vandalism"], 
  "non-violent": 
     ["Civil Sidewalks", "Embezzlement", "Forgery And Counterfeiting", "Fraud", "Gambling", "Non-Criminal", "Prostitution", "Recovered Vehicle", "Burglary", "Larceny Theft", "Motor Vehicle Theft", "Robbery", "Suspicious Occ", "Suicide", "Suspicious", "Traffic Violation Arrest", "Traffic Collision", "Vehicle Impouded", "Vehicle Misplaced", "Warrant", "Weapons Carrying"] 
}


# New column for Incident Category Score
crime_df['IncidentCategoryScore'] = np.where(crime_df['Incident Category'].isin(crime['violent']), 3, 0)
crime_df['IncidentCategoryScore'] = np.where(np.logical_and(crime_df['Incident Category'].isin( crime['non-violent']), crime_df['IncidentCategoryScore']== 0), 2, crime_df['IncidentCategoryScore'])
crime_df['IncidentCategoryScore'] = np.where(np.logical_and(crime_df['Incident Category'].isin(crime['disturbing-the-peace']), crime_df['IncidentCategoryScore']== 0), 1, crime_df['IncidentCategoryScore'])

crime_df.head(30)

             Incident Datetime  ... IncidentCategoryScore
165989  2021/08/03 11:07:00 AM  ...                     2
514077  2020/05/28 09:58:00 AM  ...                     2
132775  2021/06/03 04:19:00 PM  ...                     2
514074  2020/07/22 09:04:00 AM  ...                     2
199668  2021/12/09 06:10:00 PM  ...                     0
132767  2021/06/03 01:12:00 AM  ...                     2
50837   2020/03/28 09:27:00 PM  ...                     2
281656  2018/07/31 04:45:00 PM  ...                     1
50839   2019/12/11 06:02:00 PM  ...                     0
281649  2018/03/14 08:00:00 PM  ...                     0
514078  2020/05/22 08:05:00 AM  ...                     0
50847   2019/11/24 02:36:00 PM  ...                     2
418374  2019/01/14 11:09:00 PM  ...                     0
199689  2021/10/04 11:43:00 AM  ...                     3
50860   2019/10/09 08:30:00 PM  ...                     3
50872   2019/09/02 09:23:00 AM  ...                     0
199696  2021/10/04 08:58:00 AM  ...                     2
50874   2019/08/31 09:15:00 AM  ...                     2
514040  2020/12/15 11:52:00 AM  ...                     2
199697  2021/10/04 09:00:00 AM  ...                     3
514033  2020/10/17 09:41:00 AM  ...                     2
50848   2020/02/10 05:00:00 PM  ...                     0
132727  2021/05/24 11:00:00 AM  ...                     2
365497  2019/02/12 01:50:00 PM  ...                     2
50804   2020/03/10 03:03:00 PM  ...                     3
50745   2019/09/24 02:00:00 PM  ...                     2
514124  2021/01/02 09:05:00 AM  ...                     3
132816  2021/06/03 12:11:00 AM  ...                     3
281723  2018/05/19 01:20:00 PM  ...                     3
460608  2020/01/28 05:40:00 AM  ...                     3

[30 rows x 35 columns]

In [195]:
# Types of incidents
print(crime_df['Incident Category'].unique())

['Recovered Vehicle' 'Non-Criminal' 'Missing Person' 'Malicious Mischief'
 'Weapons Carrying Etc' 'Offences Against The Family And Children'
 'Other Miscellaneous' 'Fraud' 'Motor Vehicle Theft' 'Assault'
 'Larceny Theft' 'Lost Property' 'Burglary' 'Traffic Violation Arrest'
 'Weapons Offense' 'Forgery And Counterfeiting' 'Suspicious Occ'
 'Miscellaneous Investigation' 'Disorderly Conduct' 'Robbery' 'Warrant'
 'Other Offenses' 'Embezzlement' 'Other' 'Courtesy Report'
 'Vehicle Impounded' 'Drug Offense' 'Stolen Property' nan 'Fire Report'
 'Traffic Collision' 'Vandalism' 'Arson'
 'Human Trafficking (A), Commercial Sex Acts' 'Case Closure' 'Suicide'
 'Sex Offense' 'Vehicle Misplaced' 'Drug Violation' 'Homicide'
 'Motor Vehicle Theft?' 'Liquor Laws' 'Rape' 'Suspicious' 'Prostitution'
 'Gambling' 'Human Trafficking, Commercial Sex Acts' 'Civil Sidewalks'
 'Weapons Offence' 'Human Trafficking (B), Involuntary Servitude']

In [196]:
# See what incident descriptions are assocaited with each category

cat_desc = crime_df.groupby('Incident Category')['Incident Description'].apply(lambda x: list(np.unique(x)))
print(cat_desc)

Incident Category
Arson                                           [Arson, Arson of Vehicle, Arson with Great Bod...
Assault                                         [Assault During Labor Dispute, Assault to Comm...
Burglary                                        [Burglary, Apartment House, Att. Forcible Entr...
Case Closure                                                                       [Case Closure]
Civil Sidewalks                                 [Civil Sidewalks, Booking, Civil Sidewalks, Ci...
Courtesy Report                                                                 [Courtesy Report]
Disorderly Conduct                              [Alcohol, Under Influence Of In Public Place, ...
Drug Offense                                    [Amphetamine, Possession For Sale, Amphetamine...
Drug Violation                                  [Firearm, Armed While Possessing Controlled Su...
Embezzlement                                    [Embezzlement (general), Embezzlement, Grand T...
Fire Report                                                                         [Fire Report]
Forgery And Counterfeiting                      [Access Card or Signature, Forgery of, Checks ...
Fraud                                           [Access Card Counterfeiting Machinery, Possess...
Gambling                                        [Gambling, Gambling Devices, Possession, Gambl...
Homicide                                        [Homicide, Homicide, W/ Force, Homicide, W/ Gu...
Human Trafficking (A), Commercial Sex Acts            [Human Trafficking (A)-Commercial Sex Acts]
Human Trafficking (B), Involuntary Servitude    [Human Trafficking (B)-Involuntary Servitude (...
Human Trafficking, Commercial Sex Acts                                                  [Pimping]
Larceny Theft                                   [Burglary, Vehicle (Arrest made), Burglary, Ve...
Liquor Laws                                     [Alcohol, License Required To Sell, Alcohol, U...
Lost Property                                                                     [Lost Property]
Malicious Mischief                              [Aerosol Container; Sale, Purchase or Possessi...
Miscellaneous Investigation                     [Demonstration, Video Evidence, Misc Investiga...
Missing Person                                                      [Found Person, Missing Adult]
Motor Vehicle Theft                             [Vehicle, Recovered, Stolen outside SF, Vehicl...
Motor Vehicle Theft?                                                       [Auto, Grand Theft of]
Non-Criminal                                    [Accidental Burns, Accidental Lacerations, Aid...
Offences Against The Family And Children        [ATM-related Crime (secondary code only), Dome...
Other                                           [Death Report, Cause Unknown, Death Report, Na...
Other Miscellaneous                             [Abortion, Unlawful, Accessory or Aid Or Harbo...
Other Offenses                                  [Advertisements, Affixing To Poles, Air Gun, P...
Prostitution                                    [House of Prostitution, Keeping or Residing in...
Rape                                            [Oral Copulation, Unlawful (Adult Victim), Pen...
Recovered Vehicle                               [Vehicle, Recovered, Auto, Vehicle, Recovered,...
Robbery                                         [Carjacking with Bodily Force, Carjacking with...
Sex Offense                                     [Bathroom Hole, Looking through, Indecent Expo...
Stolen Property                                 [Money, Property or Labor, Fraudulently Obtain...
Suicide                                         [Suicide, Suicide By Asphyxiation, Suicide By ...
Suspicious                                                                   [Suspicious Package]
Suspicious Occ                                  [Suspicious Act Towards Female, Suspicious Occ...
Traffic Collision                               [Traffic Collision, Traffic Collision, Hit & R...
Traffic Violation Arrest                                               [Traffic Violation Arrest]
Vandalism                                                                    [Vehicle, Tampering]
Vehicle Impounded                                                            [Vehicle, Impounded]
Vehicle Misplaced                                                            [Vehicle, Misplaced]
Warrant                                         [Parole Search, Post Release Community Supervi...
Weapons Carrying Etc                            [Ammunition, Poss. By Prohibited Person, Armor...
Weapons Offence                                     [Weapon, Concealed, Loitering While Carrying]
Weapons Offense                                 [Caustic Chemical, Possession, Destructive Dev...
Name: Incident Description, dtype: object

In [197]:
# average incident score per neighborhood

crime_df['CS Score'] = crime_df.groupby('AnalysisNeighborhood').IncidentCategoryScore.transform('mean')

In [198]:
crime_df.columns

Index(['Incident Datetime', 'Incident Date', 'Incident Time', 'Incident Year',
       'Incident Day of Week', 'Report Datetime', 'Row ID', 'Incident ID',
       'Incident Number', 'CAD Number', 'Report Type Code',
       'Report Type Description', 'Filed Online', 'Incident Code',
       'Incident Category', 'Incident Subcategory', 'Incident Description',
       'Resolution', 'Intersection', 'CNN', 'Police District',
       'AnalysisNeighborhood', 'Supervisor District', 'Latitude', 'Longitude',
       'Point', 'Neighborhoods', 'ESNCAG - Boundary File',
       'Central Market/Tenderloin Boundary Polygon - Updated',
       'Civic Center Harm Reduction Project Boundary',
       'HSOC Zones as of 2018-06-05', 'Invest In Neighborhoods (IIN) Areas',
       'Current Supervisor Districts', 'Current Police Districts',
       'IncidentCategoryScore', 'CS Score'],
      dtype='object')

In [58]:
# export to csv and download
from google.colab import files
crime_df.to_csv('Total Crime Final.csv') 
files.download('Total Crime Final.csv')

In [199]:
clean_crime_df = crime_df.drop(columns = ['Incident Datetime', 'Incident Date', 'Incident Time', 'Incident Year',
       'Incident Day of Week', 'Report Datetime', 'Row ID', 'Incident ID',
       'Incident Number', 'CAD Number', 'Report Type Code',
       'Report Type Description', 'Filed Online', 'Incident Code',
       'Incident Category', 'Incident Subcategory', 'Incident Description',
       'Resolution', 'Intersection', 'CNN', 'Police District',
        'Supervisor District', 'Latitude', 'Longitude',
       'Point', 'Neighborhoods', 'ESNCAG - Boundary File',
       'Central Market/Tenderloin Boundary Polygon - Updated',
       'Civic Center Harm Reduction Project Boundary',
       'HSOC Zones as of 2018-06-05', 'Invest In Neighborhoods (IIN) Areas',
       'Current Supervisor Districts', 'IncidentCategoryScore', 'Current Police Districts',
       ])

In [200]:
clean_crime_df.head()

         AnalysisNeighborhood  CS Score
165989  Bayview Hunters Point    1.7384
514077  Bayview Hunters Point    1.7384
132775  Bayview Hunters Point    1.7384
514074  Bayview Hunters Point    1.7384
199668  Bayview Hunters Point    1.7384

In [201]:
clean_crime_df = clean_crime_df.drop_duplicates(subset=['AnalysisNeighborhood'])

In [202]:
clean_crime_df.head()

         AnalysisNeighborhood  CS Score
165989  Bayview Hunters Point  1.738400
222500         Bernal Heights  1.788646
472302    Castro/Upper Market  1.791669
183204              Chinatown  1.565266
247402              Excelsior  1.705869

## Prepping Neighborhood Dataset

In [203]:
neighborhood_df.head()

                                            the_geom  ...     SHAPE_LEN
0  MULTIPOLYGON (((-122.43246699970955 37.7737570...  ...   7589.679396
1  MULTIPOLYGON (((-122.4235409996432 37.77967400...  ...   8525.808755
2  MULTIPOLYGON (((-122.42468700019211 37.7853350...  ...   8000.966619
3  MULTIPOLYGON (((-122.42468700019211 37.7853350...  ...  12144.016761
4  MULTIPOLYGON (((-122.43491799981281 37.7858759...  ...   6918.268026

[5 rows x 6 columns]

In [204]:
# Rename NHOOD column to match Community Resiliency column
neighborhood_df = neighborhood_df.rename(columns = {'NHOOD' : 'AnalysisNeighborhood'})

In [205]:
neighborhood_df.head()

                                            the_geom  ...     SHAPE_LEN
0  MULTIPOLYGON (((-122.43246699970955 37.7737570...  ...   7589.679396
1  MULTIPOLYGON (((-122.4235409996432 37.77967400...  ...   8525.808755
2  MULTIPOLYGON (((-122.42468700019211 37.7853350...  ...   8000.966619
3  MULTIPOLYGON (((-122.42468700019211 37.7853350...  ...  12144.016761
4  MULTIPOLYGON (((-122.43491799981281 37.7858759...  ...   6918.268026

[5 rows x 6 columns]

In [206]:
neighborhood_df = neighborhood_df.sort_values('AnalysisNeighborhood')

In [207]:
neighborhood_df['AnalysisNeighborhood'].unique()

array(['Bayview Hunters Point', 'Bernal Heights', 'Castro/Upper Market',
       'Chinatown', 'Excelsior', 'Financial District/South Beach',
       'Glen Park', 'Golden Gate Park', 'Haight Ashbury', 'Hayes Valley',
       'Inner Richmond', 'Inner Sunset', 'Japantown', 'Lakeshore',
       'Lincoln Park', 'Lone Mountain/USF', 'Marina', 'McLaren Park',
       'Mission', 'Mission Bay', 'Nob Hill', 'Noe Valley', 'North Beach',
       'Oceanview/Merced/Ingleside', 'Outer Mission', 'Outer Richmond',
       'Pacific Heights', 'Portola', 'Potrero Hill', 'Presidio',
       'Presidio Heights', 'Russian Hill', 'Seacliff', 'South of Market',
       'Sunset/Parkside', 'Tenderloin', 'Treasure Island', 'Twin Peaks',
       'Visitacion Valley', 'West of Twin Peaks', 'Western Addition'],
      dtype=object)

## Merging Datasets

In [208]:
mlprop_df['AnalysisNeighborhood'].unique()

array(['Bayview Hunters Point', 'Bernal Heights', 'Castro/Upper Market',
       'Chinatown', 'Excelsior', 'Financial District/South Beach',
       'Glen Park', 'Golden Gate Park', 'Haight Ashbury', 'Hayes Valley',
       'Inner Richmond', 'Inner Sunset', 'Japantown', 'Lakeshore',
       'Lincoln Park', 'Lone Mountain/USF', 'Marina', 'McLaren Park',
       'Mission', 'Mission Bay', 'Nob Hill', 'Noe Valley', 'North Beach',
       'Oceanview/Merced/Ingleside', 'Outer Mission', 'Outer Richmond',
       'Pacific Heights', 'Portola', 'Potrero Hill', 'Presidio',
       'Presidio Heights', 'Russian Hill', 'Seacliff', 'South of Market',
       'Sunset/Parkside', 'Tenderloin', 'Twin Peaks', 'Visitacion Valley',
       'West of Twin Peaks', 'Western Addition'], dtype=object)

In [209]:
clean_crime_df['AnalysisNeighborhood'].unique()

array(['Bayview Hunters Point', 'Bernal Heights', 'Castro/Upper Market',
       'Chinatown', 'Excelsior', 'Financial District/South Beach',
       'Glen Park', 'Golden Gate Park', 'Haight Ashbury', 'Hayes Valley',
       'Inner Richmond', 'Inner Sunset', 'Japantown', 'Lakeshore',
       'Lincoln Park', 'Lone Mountain/USF', 'Marina', 'McLaren Park',
       'Mission', 'Mission Bay', 'Nob Hill', 'Noe Valley', 'North Beach',
       'Oceanview/Merced/Ingleside', 'Outer Mission', 'Outer Richmond',
       'Pacific Heights', 'Portola', 'Potrero Hill', 'Presidio',
       'Presidio Heights', 'Russian Hill', 'Seacliff', 'South of Market',
       'Sunset/Parkside', 'Tenderloin', 'Treasure Island', 'Twin Peaks',
       'Visitacion Valley', 'West of Twin Peaks', 'Western Addition'],
      dtype=object)

In [210]:
neighborhood_df['AnalysisNeighborhood'].unique()

array(['Bayview Hunters Point', 'Bernal Heights', 'Castro/Upper Market',
       'Chinatown', 'Excelsior', 'Financial District/South Beach',
       'Glen Park', 'Golden Gate Park', 'Haight Ashbury', 'Hayes Valley',
       'Inner Richmond', 'Inner Sunset', 'Japantown', 'Lakeshore',
       'Lincoln Park', 'Lone Mountain/USF', 'Marina', 'McLaren Park',
       'Mission', 'Mission Bay', 'Nob Hill', 'Noe Valley', 'North Beach',
       'Oceanview/Merced/Ingleside', 'Outer Mission', 'Outer Richmond',
       'Pacific Heights', 'Portola', 'Potrero Hill', 'Presidio',
       'Presidio Heights', 'Russian Hill', 'Seacliff', 'South of Market',
       'Sunset/Parkside', 'Tenderloin', 'Treasure Island', 'Twin Peaks',
       'Visitacion Valley', 'West of Twin Peaks', 'Western Addition'],
      dtype=object)

In [211]:
crimeprop_df = pd.merge(mlprop_df,clean_crime_df, how ='outer', on ='AnalysisNeighborhood')
crimeprop_df

              AnalysisNeighborhood   AvgHomeCost  CS Score
0            Bayview Hunters Point  3.496021e+05  1.738400
1                   Bernal Heights  4.817842e+05  1.788646
2              Castro/Upper Market  8.034330e+05  1.791669
3                        Chinatown  9.457721e+05  1.565266
4                        Excelsior  3.444720e+05  1.705869
5   Financial District/South Beach  1.121083e+06  1.737062
6                        Glen Park  5.779448e+05  1.857835
7                 Golden Gate Park  4.224318e+06  1.681249
8                   Haight Ashbury  8.288059e+05  1.781447
9                     Hayes Valley  8.016554e+05  1.813581
10                  Inner Richmond  6.943029e+05  1.708699
11                    Inner Sunset  6.031309e+05  1.805232
12                       Japantown  5.065034e+05  1.829474
13                       Lakeshore  2.803594e+06  1.735369
14                    Lincoln Park  8.715481e+05  1.872705
15               Lone Mountain/USF  6.551503e+05  1.723252
16                          Marina  1.167930e+06  1.844743
17                    McLaren Park  3.311654e+05  1.862969
18                         Mission  6.340985e+05  1.689780
19                     Mission Bay  1.019381e+06  1.596393
20                        Nob Hill  1.067856e+06  1.741671
21                      Noe Valley  7.476375e+05  1.926499
22                     North Beach  8.342235e+05  1.761552
23      Oceanview/Merced/Ingleside  3.457159e+05  1.696323
24                   Outer Mission  3.666917e+05  1.644503
25                  Outer Richmond  5.516745e+05  1.770224
26                 Pacific Heights  1.467162e+06  1.863274
27                         Portola  3.583265e+05  1.795470
28                    Potrero Hill  6.390039e+05  1.826707
29                        Presidio  3.636486e+06  1.755466
30                Presidio Heights  1.458371e+06  1.833578
31                    Russian Hill  1.013545e+06  1.825446
32                        Seacliff  1.558257e+06  1.902571
33                 South of Market  8.435418e+05  1.679589
34                 Sunset/Parkside  4.284264e+05  1.678197
35                      Tenderloin  1.505361e+06  1.607351
36                      Twin Peaks  6.522030e+05  1.857459
37               Visitacion Valley  3.125011e+05  1.676561
38              West of Twin Peaks  5.782016e+05  1.801446
39                Western Addition  6.644454e+05  1.717160
40                 Treasure Island           NaN  1.694952

In [212]:
crimeprop_df

              AnalysisNeighborhood   AvgHomeCost  CS Score
0            Bayview Hunters Point  3.496021e+05  1.738400
1                   Bernal Heights  4.817842e+05  1.788646
2              Castro/Upper Market  8.034330e+05  1.791669
3                        Chinatown  9.457721e+05  1.565266
4                        Excelsior  3.444720e+05  1.705869
5   Financial District/South Beach  1.121083e+06  1.737062
6                        Glen Park  5.779448e+05  1.857835
7                 Golden Gate Park  4.224318e+06  1.681249
8                   Haight Ashbury  8.288059e+05  1.781447
9                     Hayes Valley  8.016554e+05  1.813581
10                  Inner Richmond  6.943029e+05  1.708699
11                    Inner Sunset  6.031309e+05  1.805232
12                       Japantown  5.065034e+05  1.829474
13                       Lakeshore  2.803594e+06  1.735369
14                    Lincoln Park  8.715481e+05  1.872705
15               Lone Mountain/USF  6.551503e+05  1.723252
16                          Marina  1.167930e+06  1.844743
17                    McLaren Park  3.311654e+05  1.862969
18                         Mission  6.340985e+05  1.689780
19                     Mission Bay  1.019381e+06  1.596393
20                        Nob Hill  1.067856e+06  1.741671
21                      Noe Valley  7.476375e+05  1.926499
22                     North Beach  8.342235e+05  1.761552
23      Oceanview/Merced/Ingleside  3.457159e+05  1.696323
24                   Outer Mission  3.666917e+05  1.644503
25                  Outer Richmond  5.516745e+05  1.770224
26                 Pacific Heights  1.467162e+06  1.863274
27                         Portola  3.583265e+05  1.795470
28                    Potrero Hill  6.390039e+05  1.826707
29                        Presidio  3.636486e+06  1.755466
30                Presidio Heights  1.458371e+06  1.833578
31                    Russian Hill  1.013545e+06  1.825446
32                        Seacliff  1.558257e+06  1.902571
33                 South of Market  8.435418e+05  1.679589
34                 Sunset/Parkside  4.284264e+05  1.678197
35                      Tenderloin  1.505361e+06  1.607351
36                      Twin Peaks  6.522030e+05  1.857459
37               Visitacion Valley  3.125011e+05  1.676561
38              West of Twin Peaks  5.782016e+05  1.801446
39                Western Addition  6.644454e+05  1.717160
40                 Treasure Island           NaN  1.694952

In [213]:
fullmerged_df = pd.merge(crimeprop_df,neighborhood_df, how ='left', on ='AnalysisNeighborhood')
fullmerged_df.head()

    AnalysisNeighborhood   AvgHomeCost  ...    SHAPE_AREA     SHAPE_LEN
0  Bayview Hunters Point  349602.14105  ...  9.199162e+06  14909.460814
1  Bayview Hunters Point  349602.14105  ...  5.389498e+06  13510.239832
2  Bayview Hunters Point  349602.14105  ...  6.851881e+06  11841.813398
3  Bayview Hunters Point  349602.14105  ...  9.188984e+06  12565.420953
4  Bayview Hunters Point  349602.14105  ...  7.169673e+06  12082.814259

[5 rows x 8 columns]

In [214]:
#Drop unnecessary columns in full merged dataframe
fullmerged_df.drop('GEOID', axis=1, inplace=True)
fullmerged_df.drop('SHAPE_AREA', axis=1, inplace=True)
fullmerged_df.drop('SHAPE_LEN', axis=1, inplace=True)

In [215]:
fullmerged_df

      AnalysisNeighborhood  ...  TRACTCE10
0    Bayview Hunters Point  ...      23200
1    Bayview Hunters Point  ...      23102
2    Bayview Hunters Point  ...      23300
3    Bayview Hunters Point  ...      23400
4    Bayview Hunters Point  ...      23001
..                     ...  ...        ...
190       Western Addition  ...      15100
191       Western Addition  ...      15801
192       Western Addition  ...      15900
193       Western Addition  ...      16100
194        Treasure Island  ...      17902

[195 rows x 5 columns]

## Prepping Community Dataset

In [216]:
community_df.head()

          Neighborhood  Flood_Per  Heat_Per  ...  Dem_Score  Res_Score  Res_Rank
0              Bayview   0.068369  0.586532  ...        1.0        1.0      35.0
1       Bernal Heights   0.000000  0.104888  ...        3.0        3.0      16.0
2  Castro/Upper Market   0.000000  0.002686  ...        5.0        5.0       2.0
3            Chinatown   0.000000  0.999761  ...        1.0        1.0      36.0
4       Crocker Amazon   0.000000  0.218043  ...        1.0        1.0      30.0

[5 rows x 51 columns]

In [217]:
community_df = community_df.rename(columns = {'Neighborhood' : 'AnalysisNeighborhood'})

In [218]:
print(community_df['AnalysisNeighborhood'].unique())

['Bayview' 'Bernal Heights' 'Castro/Upper Market' 'Chinatown'
 'Crocker Amazon' 'Diamond Heights/Glen Park' 'Downtown/Civic Center'
 'Excelsior' 'Financial District' 'Golden Gate Park' 'Haight Ashbury'
 'Inner Richmond' 'Inner Sunset' 'Lakeshore' 'Marina' 'Mission'
 'Mission Bay' 'Nob Hill' 'Noe Valley' 'North Beach' 'Ocean View'
 'Outer Mission' 'Outer Richmond' 'Outer Sunset' 'Pacific Heights'
 'Parkside' 'Potrero Hill' 'Presidio' 'Presidio Heights' 'Russian Hill'
 'Seacliff' 'South of Market' 'Treasure Island YBI' 'Twin Peaks'
 'Visitacion Valley' 'West of Twin Peaks' 'Western Addition']

In [219]:
# rename neighborhoods within dataframes to match the community neighborhoods

fullmerged_df.loc[fullmerged_df.TRACTCE10 == 26303, 'AnalysisNeighborhood'] = "Crocker Amazon"
fullmerged_df.loc[fullmerged_df.TRACTCE10 == 35201, 'AnalysisNeighborhood'] = "Outer Sunset"
fullmerged_df.loc[fullmerged_df.TRACTCE10 == 35202, 'AnalysisNeighborhood'] = "Outer Sunset"
fullmerged_df.loc[fullmerged_df.TRACTCE10 == 35100, 'AnalysisNeighborhood'] = "Outer Sunset"
fullmerged_df.loc[fullmerged_df.TRACTCE10 == 32700, 'AnalysisNeighborhood'] = "Outer Sunset"
fullmerged_df.loc[fullmerged_df.TRACTCE10 == 32902, 'AnalysisNeighborhood'] = "Outer Sunset"
fullmerged_df.loc[fullmerged_df.TRACTCE10 == 32802, 'AnalysisNeighborhood'] = "Outer Sunset"
fullmerged_df.loc[fullmerged_df.TRACTCE10 == 32601, 'AnalysisNeighborhood'] = "Outer Sunset"
fullmerged_df.loc[fullmerged_df.TRACTCE10 == 33100, 'AnalysisNeighborhood'] = "Parkside"
fullmerged_df.loc[fullmerged_df.TRACTCE10 == 35400, 'AnalysisNeighborhood'] = "Parkside"
fullmerged_df.loc[fullmerged_df.TRACTCE10 == 35300, 'AnalysisNeighborhood'] = "Parkside"
fullmerged_df.loc[fullmerged_df.TRACTCE10 == 32901, 'AnalysisNeighborhood'] = "Parkside"
fullmerged_df.loc[fullmerged_df.TRACTCE10 == 33000, 'AnalysisNeighborhood'] = "Parkside"
fullmerged_df.loc[fullmerged_df.TRACTCE10 == 32801, 'AnalysisNeighborhood'] = "Parkside"

fullmerged_df['AnalysisNeighborhood'] = fullmerged_df['AnalysisNeighborhood'].replace({'Bayview Hunters Point': 'Bayview', 'Glen Park': 'Diamond Heights/Glen Park', 'Tenderloin':'Downtown/Civic Center','Hayes Valley': 'Downtown/Civic Center', 'Japantown': 'Pacific Heights', 'Lincoln Park':'Outer Richmond','Lone Mountain/USF':'Western Addition', 'McLaren Park': 'Excelsior', 'Oceanview/Merced/Ingleside':'Ocean View', 'Presidio Heights':'Presidio', 'Portola':'Excelsior'})
community_df['AnalysisNeighborhood'] = community_df['AnalysisNeighborhood'].replace({'Financial District': 'Financial District/South Beach', 'Treasure Island YBI': 'Treasure Island'})

In [252]:
# rename neighborhoods within dataframes to match the community neighborhoods

neighborhood_df.loc[neighborhood_df.TRACTCE10 == 26303, 'AnalysisNeighborhood'] = "Crocker Amazon"
neighborhood_df.loc[neighborhood_df.TRACTCE10 == 35201, 'AnalysisNeighborhood'] = "Outer Sunset"
neighborhood_df.loc[neighborhood_df.TRACTCE10 == 35202, 'AnalysisNeighborhood'] = "Outer Sunset"
neighborhood_df.loc[neighborhood_df.TRACTCE10 == 35100, 'AnalysisNeighborhood'] = "Outer Sunset"
neighborhood_df.loc[neighborhood_df.TRACTCE10 == 32700, 'AnalysisNeighborhood'] = "Outer Sunset"
neighborhood_df.loc[neighborhood_df.TRACTCE10 == 32902, 'AnalysisNeighborhood'] = "Outer Sunset"
neighborhood_df.loc[neighborhood_df.TRACTCE10 == 32802, 'AnalysisNeighborhood'] = "Outer Sunset"
neighborhood_df.loc[neighborhood_df.TRACTCE10 == 32601, 'AnalysisNeighborhood'] = "Outer Sunset"
neighborhood_df.loc[neighborhood_df.TRACTCE10 == 33100, 'AnalysisNeighborhood'] = "Parkside"
neighborhood_df.loc[neighborhood_df.TRACTCE10 == 35400, 'AnalysisNeighborhood'] = "Parkside"
neighborhood_df.loc[neighborhood_df.TRACTCE10 == 35300, 'AnalysisNeighborhood'] = "Parkside"
neighborhood_df.loc[neighborhood_df.TRACTCE10 == 32901, 'AnalysisNeighborhood'] = "Parkside"
neighborhood_df.loc[neighborhood_df.TRACTCE10 == 33000, 'AnalysisNeighborhood'] = "Parkside"
neighborhood_df.loc[neighborhood_df.TRACTCE10 == 32801, 'AnalysisNeighborhood'] = "Parkside"

neighborhood_df['AnalysisNeighborhood'] = neighborhood_df['AnalysisNeighborhood'].replace({'Bayview Hunters Point': 'Bayview', 'Glen Park': 'Diamond Heights/Glen Park', 'Tenderloin':'Downtown/Civic Center','Hayes Valley': 'Downtown/Civic Center', 'Japantown': 'Pacific Heights', 'Lincoln Park':'Outer Richmond','Lone Mountain/USF':'Western Addition', 'McLaren Park': 'Excelsior', 'Oceanview/Merced/Ingleside':'Ocean View', 'Presidio Heights':'Presidio', 'Portola':'Excelsior'})

In [220]:
print(fullmerged_df['AnalysisNeighborhood'].unique())

['Bayview' 'Bernal Heights' 'Castro/Upper Market' 'Chinatown' 'Excelsior'
 'Crocker Amazon' 'Financial District/South Beach'
 'Diamond Heights/Glen Park' 'Golden Gate Park' 'Haight Ashbury'
 'Downtown/Civic Center' 'Inner Richmond' 'Inner Sunset' 'Pacific Heights'
 'Lakeshore' 'Outer Richmond' 'Western Addition' 'Marina' 'Mission'
 'Mission Bay' 'Nob Hill' 'Noe Valley' 'North Beach' 'Ocean View'
 'Outer Mission' 'Potrero Hill' 'Presidio' 'Russian Hill' 'Seacliff'
 'South of Market' 'Outer Sunset' 'Sunset/Parkside' 'Parkside'
 'Twin Peaks' 'Visitacion Valley' 'West of Twin Peaks' 'Treasure Island']

In [221]:
print(community_df['AnalysisNeighborhood'].unique())

['Bayview' 'Bernal Heights' 'Castro/Upper Market' 'Chinatown'
 'Crocker Amazon' 'Diamond Heights/Glen Park' 'Downtown/Civic Center'
 'Excelsior' 'Financial District/South Beach' 'Golden Gate Park'
 'Haight Ashbury' 'Inner Richmond' 'Inner Sunset' 'Lakeshore' 'Marina'
 'Mission' 'Mission Bay' 'Nob Hill' 'Noe Valley' 'North Beach'
 'Ocean View' 'Outer Mission' 'Outer Richmond' 'Outer Sunset'
 'Pacific Heights' 'Parkside' 'Potrero Hill' 'Presidio' 'Presidio Heights'
 'Russian Hill' 'Seacliff' 'South of Market' 'Treasure Island'
 'Twin Peaks' 'Visitacion Valley' 'West of Twin Peaks' 'Western Addition']

In [222]:
# export to csv and download
community_df.to_csv('Community Final.csv') 
files.download('Community Final.csv')

In [223]:
fullmerged_df.to_csv('Property, Crime, Neighborhood Final.csv') 
files.download('Property, Crime, Neighborhood Final.csv')

## Final Merge of Datasets

In [228]:
# Merge geospatial data for neighborhoods into Community Resiliency
fullML_df = pd.merge(fullmerged_df,community_df, how ='left', on ='AnalysisNeighborhood')

fullML_df.head()

  AnalysisNeighborhood   AvgHomeCost  CS Score  ... Dem_Score  Res_Score  Res_Rank
0              Bayview  349602.14105    1.7384  ...       1.0        1.0      35.0
1              Bayview  349602.14105    1.7384  ...       1.0        1.0      35.0
2              Bayview  349602.14105    1.7384  ...       1.0        1.0      35.0
3              Bayview  349602.14105    1.7384  ...       1.0        1.0      35.0
4              Bayview  349602.14105    1.7384  ...       1.0        1.0      35.0

[5 rows x 55 columns]

In [225]:
fullML_df = fullML_df.drop('TRACTCE10', axis=1, inplace=True)

In [230]:
#Data Frame for machine learning model features

features_df = fullML_df.drop(['Flood_Per', 'Heat_Per', 'Liq_Per',
       'Haz_Score', 'Imp_Per', 'Tree_Per', 'PM_Conc', 'Tox_Per', 'Env_Score',
       'AT_Min', 'Vot_Rate',
       'NewSF_Per', 'Citz_Per', 'Eng_Per', 'Com_Score', 'Food_Score', 'HS_Per',
       'Pharm_Per', 'PR_Score', 'OC_Per',
        'AC_Per', 'Rent_Per', 'House_Score', 
       'Shelt_Rate', 'SheltDay_Rate', 'Dis_Per', 'PrevHos', 'Health_Score',
       'Over85_Per', 'Over65_Per', 'Under18_Per', 'Under5_Per', 'NonWhi_Per',
       'Lat_Per', 'Black_Per', 'Asian_Per', 'Dem_Score','Res_Rank'], axis = 1)

In [231]:
features_df.dtypes

AnalysisNeighborhood     object
AvgHomeCost             float64
CS Score                float64
the_geom                 object
TRACTCE10                 int64
PTrans_Sco              float64
Trans_Sco               float64
VCrim_Rate              float64
LivAl_Per               float64
EldLivAl_Per            float64
Viol_Rate               float64
Emp_per                 float64
Ec_Score                float64
Pov_Per                 float64
PopDens                 float64
DayPopDens              float64
Res_Score               float64
dtype: object

In [238]:
features_df

    AnalysisNeighborhood    AvgHomeCost  ...  DayPopDens Res_Score
0                Bayview  349602.141050  ...     9850.25       1.0
1                Bayview  349602.141050  ...     9850.25       1.0
2                Bayview  349602.141050  ...     9850.25       1.0
3                Bayview  349602.141050  ...     9850.25       1.0
4                Bayview  349602.141050  ...     9850.25       1.0
..                   ...            ...  ...         ...       ...
190     Western Addition  664445.419909  ...    25633.70       3.0
191     Western Addition  664445.419909  ...    25633.70       3.0
192     Western Addition  664445.419909  ...    25633.70       3.0
193     Western Addition  664445.419909  ...    25633.70       3.0
194      Treasure Island            NaN  ...     2963.89       1.0

[195 rows x 17 columns]

In [233]:
# Export to CSV
from google.colab import files
features_df.to_csv('Machine Learning Features.csv')
files.download('Machine Learning Features.csv')

In [239]:
from shapely.geometry import Point

In [263]:
features_df = gpd.GeoDataFrame(features_df, geometry='the_geom')

# proj WGS84

features_df.crs= "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"

features_df.to_file('features.shp', driver='ESRI Shapefile')

TypeError: ignored

In [262]:
from shapely import wkt

# previous lines

crs_code = 32637

features_df['the_geom'] = features_df.geometry.apply(wkt.loads)
features_df = GeoDataFrame(features_df, crs=crs_code)

features_df.gpd.to_file('features.shp', driver='ESRI Shapefile')

AttributeError: ignored

In [240]:
from google.colab import files
features_df.to_file('features.shp')
files.download('features.shp')

AttributeError: ignored

# Database Creation + Integration

In [245]:
# Creating the database and importing the csv data into the tables

# Import required modules
import sqlite3
from sqlalchemy import create_engine

In [246]:
# Connecting to the database
connection = sqlite3.connect('final_project.db')

In [253]:
# Send dataframes to the database
famprop_df.to_sql(name = "property",con=connection, if_exists= 'replace', index = False)
crime_df.to_sql(name = "crime",con=connection, if_exists= 'replace', index = False)
neighborhood_df.to_sql(name = "neighborhood",con=connection, if_exists= 'replace', index = False)
community_df.to_sql(name = "community",con=connection, if_exists= 'replace', index = False)

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:2615: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  method=method,

In [254]:
connection.commit()

## Query Database

In [261]:
# Average goal by team

cursor = connection.execute(''' SELECT * FROM crime LIMIT 10;''').headers

for row in cursor:
  print(row)
connection.close()

ProgrammingError: ignored

# Machine Learning

In [ ]:
# Imports for machine learning model

import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

In [ ]:
#Skeleton for our model

# Load the data
file_path = Path('./Resources/LoanStats_2019Q1.csv')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_crime'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_crime')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

df.head()

In [ ]:
# Create our features
X = df.drop("Incident Severity", axis=1)

X = pd.get_dummies(X)

# Create our target
y = df["Incident Severity"]

In [ ]:
X.describe()

In [ ]:
# Check the balance of our target values
y.value_counts()

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

##Balanced Random Forest Classifier

In [ ]:
# Resample the training data with the BalancedRandomForestClassifier

from imblearn.ensemble import BalancedRandomForestClassifier
random_forest = BalancedRandomForestClassifier(n_estimators = 100)
random_forest = random_forest.fit(X_train, y_train)

In [ ]:
# Calculated the balanced accuracy score

from sklearn.metrics import balanced_accuracy_score
y_pred = random_forest.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

In [ ]:
# Display the confusion matrix

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

In [ ]:
# Print the imbalanced classification report

from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

In [ ]:
# List the features sorted in descending order by feature importance

feature_names = X.columns
sorted(zip(random_forest.feature_importances_, feature_names), reverse=True)

# Visualizing the Data

# Conclusion of Project and Future Analysis